### ISSUE TITLE
Do wireframing/prototyping for design

### ISSUE THREAD

**Issue by mathildaduku** [preciousyaks17/Tracksify-Frontend#8]

**Comment by veffiong73** [comment]
Done 

Employer - https://www.figma.com/proto/mFtdEDjRedFGyHYMPIJiU9/Untitled?type=design&node-id=596-655&t=wj9zoYST8C85FF5R-1&scaling=scale-down&page-id=596%3A528&starting-point-node-id=596%3A547&mode=design

Employee - https://www.figma.com/proto/mFtdEDjRedFGyHYMPIJiU9/Untitled?type=design&node-id=569-184&t=j5e3ldwJ9XhbavmU-1&scaling=min-zoom&page-id=569%3A165&starting-point-node-id=569%3A184&mode=design
